// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/api/v1/greeter/greeter.proto

package greeter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetingStyle int32

const (
	GreetingStyle_GREETING_STYLE_UNSPECIFIED  GreetingStyle = 0
	GreetingStyle_GREETING_STYLE_FORMAL       GreetingStyle = 1
	GreetingStyle_GREETING_STYLE_CASUAL       GreetingStyle = 2
	GreetingStyle_GREETING_STYLE_ENTHUSIASTIC GreetingStyle = 3
)

// Enum value maps for GreetingStyle.
var (
	GreetingStyle_name = map[int32]string{
		0: "GREETING_STYLE_UNSPECIFIED",
		1: "GREETING_STYLE_FORMAL",
		2: "GREETING_STYLE_CASUAL",
		3: "GREETING_STYLE_ENTHUSIASTIC",
	}
	GreetingStyle_value = map[string]int32{
		"GREETING_STYLE_UNSPECIFIED":  0,
		"GREETING_STYLE_FORMAL":       1,
		"GREETING_STYLE_CASUAL":       2,
		"GREETING_STYLE_ENTHUSIASTIC": 3,
	}
)

func (x GreetingStyle) Enum() *GreetingStyle {
	p := new(GreetingStyle)
	*p = x
	return p
}

func (x GreetingStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GreetingStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_v1_greeter_greeter_proto_enumTypes[0].Descriptor()
}

func (GreetingStyle) Type() protoreflect.EnumType {
	return &file_proto_api_v1_greeter_greeter_proto_enumTypes[0]
}

func (x GreetingStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GreetingStyle.Descriptor instead.
func (GreetingStyle) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_v1_greeter_greeter_proto_rawDescGZIP(), []int{0}
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Style         GreetingStyle          `protobuf:"varint,2,opt,name=style,proto3,enum=myorg.api.v1.greeter.GreetingStyle" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_api_v1_greeter_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_greeter_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_greeter_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetStyle() GreetingStyle {
	if x != nil {
		return x.Style
	}
	return GreetingStyle_GREETING_STYLE_UNSPECIFIED
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_proto_api_v1_greeter_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_greeter_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_greeter_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloReply) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

var File_proto_api_v1_greeter_greeter_proto protoreflect.FileDescriptor

const file_proto_api_v1_greeter_greeter_proto_rawDesc = "" +
	"\n" +
	"\"proto/api/v1/greeter/greeter.proto\x12\x14myorg.api.v1.greeter\"]\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\x05style\x18\x02 \x01(\x0e2#.myorg.api.v1.greeter.GreetingStyleR\x05style\"M\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix*\x86\x01\n" +
	"\rGreetingStyle\x12\x1e\n" +
	"\x1aGREETING_STYLE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15GREETING_STYLE_FORMAL\x10\x01\x12\x19\n" +
	"\x15GREETING_STYLE_CASUAL\x10\x02\x12\x1f\n" +
	"\x1bGREETING_STYLE_ENTHUSIASTIC\x10\x032\xbc\x01\n" +
	"\x0eGreeterService\x12P\n" +
	"\bSayHello\x12\".myorg.api.v1.greeter.HelloRequest\x1a .myorg.api.v1.greeter.HelloReply\x12X\n" +
	"\x0eSayHelloStream\x12\".myorg.api.v1.greeter.HelloRequest\x1a .myorg.api.v1.greeter.HelloReply0\x01B5Z3github.com/TerrenceHo/monorepo/proto/api/v1/greeterb\x06proto3"

var (
	file_proto_api_v1_greeter_greeter_proto_rawDescOnce sync.Once
	file_proto_api_v1_greeter_greeter_proto_rawDescData []byte
)

func file_proto_api_v1_greeter_greeter_proto_rawDescGZIP() []byte {
	file_proto_api_v1_greeter_greeter_proto_rawDescOnce.Do(func() {
		file_proto_api_v1_greeter_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_v1_greeter_greeter_proto_rawDesc), len(file_proto_api_v1_greeter_greeter_proto_rawDesc)))
	})
	return file_proto_api_v1_greeter_greeter_proto_rawDescData
}

var file_proto_api_v1_greeter_greeter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_api_v1_greeter_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_api_v1_greeter_greeter_proto_goTypes = []any{
	(GreetingStyle)(0),   // 0: myorg.api.v1.greeter.GreetingStyle
	(*HelloRequest)(nil), // 1: myorg.api.v1.greeter.HelloRequest
	(*HelloReply)(nil),   // 2: myorg.api.v1.greeter.HelloReply
}
var file_proto_api_v1_greeter_greeter_proto_depIdxs = []int32{
	0, // 0: myorg.api.v1.greeter.HelloRequest.style:type_name -> myorg.api.v1.greeter.GreetingStyle
	1, // 1: myorg.api.v1.greeter.GreeterService.SayHello:input_type -> myorg.api.v1.greeter.HelloRequest
	1, // 2: myorg.api.v1.greeter.GreeterService.SayHelloStream:input_type -> myorg.api.v1.greeter.HelloRequest
	2, // 3: myorg.api.v1.greeter.GreeterService.SayHello:output_type -> myorg.api.v1.greeter.HelloReply
	2, // 4: myorg.api.v1.greeter.GreeterService.SayHelloStream:output_type -> myorg.api.v1.greeter.HelloReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_api_v1_greeter_greeter_proto_init() }
func file_proto_api_v1_greeter_greeter_proto_init() {
	if File_proto_api_v1_greeter_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_v1_greeter_greeter_proto_rawDesc), len(file_proto_api_v1_greeter_greeter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_v1_greeter_greeter_proto_goTypes,
		DependencyIndexes: file_proto_api_v1_greeter_greeter_proto_depIdxs,
		EnumInfos:         file_proto_api_v1_greeter_greeter_proto_enumTypes,
		MessageInfos:      file_proto_api_v1_greeter_greeter_proto_msgTypes,
	}.Build()
	File_proto_api_v1_greeter_greeter_proto = out.File
	file_proto_api_v1_greeter_greeter_proto_goTypes = nil
	file_proto_api_v1_greeter_greeter_proto_depIdxs = nil
}
