load("//bazel/python:rules.bzl", "py_binary", "py_library")

py_binary(
    name = "ipython",
    srcs = ["ipython_entry.py"],
    main = "ipython_entry.py",
    deps = [
        "@pypi//ipython",
        "@pypi//numpy",
        "@pypi//pandas",
    ],
)

py_library(
    name = "notebooks",
    srcs = ["ipython_entry.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//ipython"],
)
